# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Depo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_depo_ekran(object):
    def setupUi(self, depo_ekran):
        depo_ekran.setObjectName("depo_ekran")
        depo_ekran.resize(920, 647)
        depo_ekran.setWindowTitle("")
        depo_ekran.setStyleSheet("background-color: rgb(82, 158, 168);")
        self.centralwidget = QtWidgets.QWidget(depo_ekran)
        self.centralwidget.setObjectName("centralwidget")
        self.depoyazi_lbl = QtWidgets.QLabel(self.centralwidget)
        self.depoyazi_lbl.setGeometry(QtCore.QRect(0, 0, 921, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.depoyazi_lbl.setFont(font)
        self.depoyazi_lbl.setStyleSheet("background-color: rgb(163, 221, 229);")
        self.depoyazi_lbl.setObjectName("depoyazi_lbl")
        self.kumaskayit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.kumaskayit_btn.setGeometry(QtCore.QRect(760, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.kumaskayit_btn.setFont(font)
        self.kumaskayit_btn.setStyleSheet("background-color: rgb(163, 221, 229);\n"
"color: rgb(34, 50, 190);")
        self.kumaskayit_btn.setObjectName("kumaskayit_btn")
        self.arabalar_img = QtWidgets.QFrame(self.centralwidget)
        self.arabalar_img.setGeometry(QtCore.QRect(180, 270, 121, 61))
        self.arabalar_img.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.arabalar_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.arabalar_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.arabalar_img.setObjectName("arabalar_img")
        self.arabalar_btn = QtWidgets.QPushButton(self.centralwidget)
        self.arabalar_btn.setGeometry(QtCore.QRect(150, 200, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.arabalar_btn.setFont(font)
        self.arabalar_btn.setStyleSheet("background-color: rgb(163, 221, 229);\n"
"color: rgb(0, 0, 0);")
        self.arabalar_btn.setObjectName("arabalar_btn")
        self.raflar_btn = QtWidgets.QPushButton(self.centralwidget)
        self.raflar_btn.setGeometry(QtCore.QRect(600, 200, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.raflar_btn.setFont(font)
        self.raflar_btn.setStyleSheet("background-color: rgb(163, 221, 229);\n"
"color: rgb(0, 0, 0);")
        self.raflar_btn.setObjectName("raflar_btn")
        self.raflar_img = QtWidgets.QFrame(self.centralwidget)
        self.raflar_img.setGeometry(QtCore.QRect(670, 260, 61, 71))
        self.raflar_img.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.raflar_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.raflar_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.raflar_img.setObjectName("raflar_img")
        self.fiberflonyazi2_lbl = QtWidgets.QLabel(self.centralwidget)
        self.fiberflonyazi2_lbl.setGeometry(QtCore.QRect(330, 490, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.fiberflonyazi2_lbl.setFont(font)
        self.fiberflonyazi2_lbl.setStyleSheet("color: rgb(34, 50, 190);")
        self.fiberflonyazi2_lbl.setObjectName("fiberflonyazi2_lbl")
        self.kumaskayit_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.kumaskayit_btn_2.setGeometry(QtCore.QRect(610, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.kumaskayit_btn_2.setFont(font)
        self.kumaskayit_btn_2.setStyleSheet("background-color: rgb(163, 221, 229);\n"
"color: rgb(34, 50, 190);")
        self.kumaskayit_btn_2.setObjectName("kumaskayit_btn_2")
        depo_ekran.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(depo_ekran)
        self.statusbar.setObjectName("statusbar")
        depo_ekran.setStatusBar(self.statusbar)

        self.retranslateUi(depo_ekran)
        QtCore.QMetaObject.connectSlotsByName(depo_ekran)

    def retranslateUi(self, depo_ekran):
        _translate = QtCore.QCoreApplication.translate
        self.depoyazi_lbl.setText(_translate("depo_ekran", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#141312;\">DEPO</span></p></body></html>"))
        self.kumaskayit_btn.setText(_translate("depo_ekran", "Kumaş Kayıt"))
        self.arabalar_btn.setText(_translate("depo_ekran", "Arabalar"))
        self.raflar_btn.setText(_translate("depo_ekran", "Raflar"))
        self.fiberflonyazi2_lbl.setText(_translate("depo_ekran", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">FİBERFLON</span></p></body></html>"))
        self.kumaskayit_btn_2.setText(_translate("depo_ekran", "Kumaş Ara"))
