# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_giris_ekran(object):
    def setupUi(self, giris_ekran):
        giris_ekran.setObjectName("giris_ekran")
        giris_ekran.resize(681, 528)
        giris_ekran.setWindowTitle("")
        giris_ekran.setStyleSheet("background-color: rgb(82, 158, 168);")
        self.centralwidget = QtWidgets.QWidget(giris_ekran)
        self.centralwidget.setObjectName("centralwidget")
        self.personel_img = QtWidgets.QFrame(self.centralwidget)
        self.personel_img.setGeometry(QtCore.QRect(280, 140, 121, 121))
        self.personel_img.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"")
        self.personel_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.personel_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.personel_img.setObjectName("personel_img")
        self.fiberflonyazi1_lbl = QtWidgets.QLabel(self.centralwidget)
        self.fiberflonyazi1_lbl.setGeometry(QtCore.QRect(0, 0, 681, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.fiberflonyazi1_lbl.setFont(font)
        self.fiberflonyazi1_lbl.setStyleSheet("background-color: rgb(163, 221, 229);")
        self.fiberflonyazi1_lbl.setObjectName("fiberflonyazi1_lbl")
        self.kullaniciadi_lbl = QtWidgets.QLabel(self.centralwidget)
        self.kullaniciadi_lbl.setGeometry(QtCore.QRect(110, 290, 141, 61))
        self.kullaniciadi_lbl.setStyleSheet("color: rgb(34, 50, 190);")
        self.kullaniciadi_lbl.setObjectName("kullaniciadi_lbl")
        self.sifre_lbl = QtWidgets.QLabel(self.centralwidget)
        self.sifre_lbl.setGeometry(QtCore.QRect(180, 340, 61, 61))
        self.sifre_lbl.setStyleSheet("color: rgb(34, 50, 190);")
        self.sifre_lbl.setObjectName("sifre_lbl")
        self.kullaniciadi_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.kullaniciadi_entry.setGeometry(QtCore.QRect(250, 300, 191, 31))
        self.kullaniciadi_entry.setStyleSheet("background-color: rgb(163, 221, 229);")
        self.kullaniciadi_entry.setObjectName("kullaniciadi_entry")
        self.sifre_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.sifre_entry.setGeometry(QtCore.QRect(250, 350, 191, 31))
        self.sifre_entry.setStyleSheet("background-color: rgb(163, 221, 229);")
        self.sifre_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifre_entry.setObjectName("sifre_entry")
        self.kullaniciadi_img = QtWidgets.QFrame(self.centralwidget)
        self.kullaniciadi_img.setGeometry(QtCore.QRect(460, 300, 41, 31))
        self.kullaniciadi_img.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"")
        self.kullaniciadi_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kullaniciadi_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kullaniciadi_img.setObjectName("kullaniciadi_img")
        self.sifre_img = QtWidgets.QFrame(self.centralwidget)
        self.sifre_img.setGeometry(QtCore.QRect(460, 350, 41, 31))
        self.sifre_img.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"")
        self.sifre_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sifre_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sifre_img.setObjectName("sifre_img")
        self.giris_btn = QtWidgets.QPushButton(self.centralwidget)
        self.giris_btn.setGeometry(QtCore.QRect(310, 410, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.giris_btn.setFont(font)
        self.giris_btn.setStyleSheet("background-color: rgb(163, 221, 229);\n"
"color: rgb(34, 50, 190);")
        self.giris_btn.setObjectName("giris_btn")
        giris_ekran.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(giris_ekran)
        self.statusbar.setObjectName("statusbar")
        giris_ekran.setStatusBar(self.statusbar)

        self.retranslateUi(giris_ekran)
        QtCore.QMetaObject.connectSlotsByName(giris_ekran)

    def retranslateUi(self, giris_ekran):
        _translate = QtCore.QCoreApplication.translate
        self.fiberflonyazi1_lbl.setText(_translate("giris_ekran", "<html><head/><body><p align=\"center\"><span style=\" color:#2232be;\">FİBERFLON</span></p></body></html>"))
        self.kullaniciadi_lbl.setText(_translate("giris_ekran", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Kullanıcı Adı :</span></p></body></html>"))
        self.sifre_lbl.setText(_translate("giris_ekran", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Şifre :</span></p></body></html>"))
        self.giris_btn.setText(_translate("giris_ekran", "Giriş"))
