# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kumas_Filtreleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kumasfiltreleme_ekran(object):
    def setupUi(self, kumasfiltreleme_ekran):
        kumasfiltreleme_ekran.setObjectName("kumasfiltreleme_ekran")
        kumasfiltreleme_ekran.resize(1303, 840)
        kumasfiltreleme_ekran.setWindowTitle("")
        kumasfiltreleme_ekran.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(kumasfiltreleme_ekran)
        self.centralwidget.setObjectName("centralwidget")
        self.kumaslaryazi_lbl = QtWidgets.QLabel(self.centralwidget)
        self.kumaslaryazi_lbl.setGeometry(QtCore.QRect(0, 0, 1311, 151))
        self.kumaslaryazi_lbl.setStyleSheet("background-color: rgb(163, 221, 229);")
        self.kumaslaryazi_lbl.setObjectName("kumaslaryazi_lbl")
        self.kumaslar_tw = QtWidgets.QTableWidget(self.centralwidget)
        self.kumaslar_tw.setGeometry(QtCore.QRect(0, 150, 1301, 701))
        self.kumaslar_tw.setBaseSize(QtCore.QSize(0, 0))
        self.kumaslar_tw.setRowCount(200)
        self.kumaslar_tw.setColumnCount(5)
        self.kumaslar_tw.setObjectName("kumaslar_tw")
        self.kumaslar_tw.horizontalHeader().setVisible(True)
        self.kumaslar_tw.horizontalHeader().setCascadingSectionResizes(False)
        self.kumaslar_tw.horizontalHeader().setDefaultSectionSize(250)
        self.kumaslar_tw.horizontalHeader().setMinimumSectionSize(38)
        self.kumaslar_tw.verticalHeader().setDefaultSectionSize(40)
        self.kumaslar_tw.verticalHeader().setMinimumSectionSize(23)
        self.kalitesec_cb = QtWidgets.QComboBox(self.centralwidget)
        self.kalitesec_cb.setGeometry(QtCore.QRect(10, 70, 261, 31))
        self.kalitesec_cb.setObjectName("kalitesec_cb")
        self.kalitesec_cb.addItem("")
        self.kalitesec_cb.addItem("")
        self.kalitesec_cb.addItem("")
        self.kalitesec_cb.addItem("")
        self.kalitesec_cb.addItem("")
        self.ks_listele_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ks_listele_btn.setGeometry(QtCore.QRect(190, 110, 81, 31))
        self.ks_listele_btn.setObjectName("ks_listele_btn")
        self.kalitesec_lbl = QtWidgets.QLabel(self.centralwidget)
        self.kalitesec_lbl.setGeometry(QtCore.QRect(0, 40, 131, 31))
        self.kalitesec_lbl.setObjectName("kalitesec_lbl")
        self.tumunulist_btn = QtWidgets.QPushButton(self.centralwidget)
        self.tumunulist_btn.setGeometry(QtCore.QRect(1100, 110, 181, 31))
        self.tumunulist_btn.setObjectName("tumunulist_btn")
        kumasfiltreleme_ekran.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(kumasfiltreleme_ekran)
        self.statusbar.setObjectName("statusbar")
        kumasfiltreleme_ekran.setStatusBar(self.statusbar)

        self.retranslateUi(kumasfiltreleme_ekran)
        QtCore.QMetaObject.connectSlotsByName(kumasfiltreleme_ekran)

    def retranslateUi(self, kumasfiltreleme_ekran):
        _translate = QtCore.QCoreApplication.translate
        self.kumaslaryazi_lbl.setText(_translate("kumasfiltreleme_ekran", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\"><br/></span><span style=\" font-size:28pt; font-weight:600; color:#2232be;\">Kumaşlar</span></p><p align=\"center\"><span style=\" font-size:28pt;\"><br/></span></p></body></html>"))
        self.kalitesec_cb.setItemText(0, _translate("kumasfiltreleme_ekran", "21615"))
        self.kalitesec_cb.setItemText(1, _translate("kumasfiltreleme_ekran", "11613"))
        self.kalitesec_cb.setItemText(2, _translate("kumasfiltreleme_ekran", "10808"))
        self.kalitesec_cb.setItemText(3, _translate("kumasfiltreleme_ekran", "82825"))
        self.kalitesec_cb.setItemText(4, _translate("kumasfiltreleme_ekran", "92825"))
        self.ks_listele_btn.setText(_translate("kumasfiltreleme_ekran", "Listele"))
        self.kalitesec_lbl.setText(_translate("kumasfiltreleme_ekran", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Kalite Seç:</span></p><p align=\"center\"><br/></p></body></html>"))
        self.tumunulist_btn.setText(_translate("kumasfiltreleme_ekran", "Tümünü Listele"))
